dependencies {

    api("com.github.GTNewHorizons:Baubles-Expanded:2.2.2-GTNH:dev")

    implementation("thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev")
    implementation("com.github.GTNewHorizons:GTNHLib:0.9.20:dev")

    compileOnly('com.github.GTNewHorizons:ThaumicBases:1.9.5:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:Thaumic_Exploration:1.5.5-GTNH:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:NewHorizonsCoreMod:2.8.142:dev')
    compileOnly('com.github.GTNewHorizons:WitchingGadgets:1.8.33-GTNH:dev')


    runtimeOnlyNonPublishable("com.github.GTNewHorizons:NotEnoughItems:2.8.37-GTNH:dev")

    //For Testing:
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:ThaumicBases:1.9.5:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:Thaumic_Exploration:1.5.5-GTNH:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:WitchingGadgets:1.8.33-GTNH:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:thaumicinsurgence:0.4.0:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:WarpTheory:1.5.0-GTNH:dev")

    //GTNH
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:NewHorizonsCoreMod:2.8.142:dev")
    //Update Hodgepodge to make Twilight Forest not crash the world on startup
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:Hodgepodge:2.7.16:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:ThaumicEnergistics:1.7.14-GTNH:dev")
    runtimeOnlyNonPublishable rfg.deobf("curse.maven:biomes-o-plenty-220318:2499612")
    runtimeOnlyNonPublishable rfg.deobf("curse.maven:witchery-69673:2234410")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:WitcheryExtras:1.4.0:dev") { transitive = false }
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:WailaHarvestability:1.3.4-GTNH:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:Galacticraft:3.4.7-GTNH:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:Electro-Magic-Tools:1.7.6:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:Chisel:2.17.14-GTNH")
    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:MagicBees:2.10.2-GTNH:dev")
    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:Ztones-Unofficial:2.3.2-GTNH:dev")
    //runtimeOnlyNonPublishable("ganymedes01.etfuturum:Et-Futurum-Requiem:2.6.2.28-GTNH:dev") { transitive = false }
    runtimeOnlyNonPublishable(rfg.deobf("curse.maven:thaumcraft-nei-plugin-225095:2241913")) { transitive = false }

    // deps may transitively add Baubles, so we replace it
    project.getConfigurations()
        .all(c -> {
            final DependencySubstitutions ds = c.getResolutionStrategy()
                .getDependencySubstitution();
            ds.substitute(ds.module("com.github.GTNewHorizons:Baubles"))
                .using(ds.module("com.github.GTNewHorizons:Baubles-Expanded:2.2.2-GTNH"))
                .withClassifier("dev")
                .because("Baubles-Expanded replaces Baubles");
        });
}
