dependencies {

    api("com.github.GTNewHorizons:Baubles-Expanded:2.2.2-GTNH:dev")

    implementation("thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev")

    compileOnly('com.github.GTNewHorizons:ThaumicBases:1.9.2:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:Thaumic_Exploration:1.5.5-GTNH:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:NewHorizonsCoreMod:2.8.31:dev')
    compileOnly('com.github.GTNewHorizons:WitchingGadgets:1.8.8-GTNH:dev')

    runtimeOnlyNonPublishable("com.github.GTNewHorizons:NotEnoughItems:2.8.37-GTNH:dev")

    //For Testing:
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:NewHorizonsCoreMod:2.8.31:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:WitchingGadgets:1.8.8-GTNH:dev")
}
